name: Build & Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CACHE_PATH: opensense-tools-cache.tar.gz

jobs:
  package:
    runs-on: macos-latest
    name: Package OPNsense plugin
    steps:
    - uses: actions/checkout@v4

    - name: Restore cache
      id: cache-restore
      uses: actions/cache/restore@v3
      with:
        path: ${{ env.CACHE_PATH }}
        key: ${{ runner.os }}-cache

    # - name: Build package
    #   id: package
    #   uses: vmactions/freebsd-vm@v0.3.1
    #   with:
    #     mem: 6144
    #     # Should match opnsense
    #     release: "13.2"
    #     prepare: |
    #       pkg install -y lang/go git bash pigz

    #       cat <<'EOF' | bash
    #       export OS=13.2
    #       set -x
    #       workdir=$(pwd)
    #       env

    #       if [ -f "$CACHE_PATH" ]; then
    #         tar -C / -xf "$CACHE_PATH"
    #       else
    #         git clone https://github.com/opnsense/tools /usr/tools
    #       fi

    #       cd /usr/tools
    #       make update
    #       cd "$workdir"

    #       time tar -cf - /usr/tools /usr/core /usr/plugins /usr/ports /usr/src | pigz > "$CACHE_PATH"
    #       EOF
    #     run: bash ci_build.sh
    - name: Setup upterm session
      uses: lhotari/action-upterm@v1

    - name: Save cache
      uses: actions/cache/save@v3
      with:
        path: ${{ env.CACHE_PATH }}
        key: ${{ runner.os }}-cache

    - name: Archive build
      uses: actions/upload-artifact@v2
      with:
        name: package
        path: build/
